swagger: '2.0'
info:
  version: '1.0'
  title: "Personal Page - Admin - NodeJS"
  description: Service that manage the text content of the Personal Page
  license:
    name: GNU General Public License v3.0
    url: https://github.com/Javier-Caballero-Info/personal_page_admin_nodejs/blob/master/LICENSE
host: 188.166.96.202:3000
schemes:
- http
consumes:
- application/json
produces:
- application/json
tags:
- name: "Contact"
- name: "Education"
- name: "Home"
- name: "Health"
- name: "Research"
- name: "Scholastic"
- name: "SocialNetwork"
- name: "Work"
paths:
  /:
    get:
      summary: Home - List All Services
      tags:
      - "Home"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            properties:
              endpoints:
                type: array
                items:
                  $ref: '#/definitions/ServiceRestFull'
            example:
              endpoints: 
              - name: "Social Networks"
                paths:
                  one:
                    method: "GET"
                    path: "/:lang/social-networks/:id"
                  all: 
                    method: "GET"
                    path: "/:lang/social-networks"
                  create:
                    method: "POST"
                    path: "/:lang/social-networks"
                  update:
                    method: "PUT"
                    path: "/:lang/social-networks/:id"
                  remove:
                    method: "DELETE"
                    path: "/:lang/social-networks/:id"
              - name: "Contacts"
                paths:
                  one:
                    method: "GET"
                    path: "/:lang/contacts/:id"
                  all: 
                    method: "GET"
                    path: "/:lang/contacts"
                  create:
                    method: "POST"
                    path: "/:lang/contacts"
                  update:
                    method: "PUT"
                    path: "/:lang/contacts/:id"
                  remove:
                    method: "DELETE"
                    path: "/:lang/contacts/:id"
              - name: "Educations"
                paths:
                  one:
                    method: "GET"
                    path: "/:lang/educations/:id"
                  all: 
                    method: "GET"
                    path: "/:lang/educations"
                  create:
                    method: "POST"
                    path: "/:lang/educations"
                  update:
                    method: "PUT"
                    path: "/:lang/educations/:id"
                  remove:
                    method: "DELETE"
                    path: "/:lang/educations/:id"
              - name: "Researches"
                paths:
                  one:
                    method: "GET"
                    path: "/:lang/researches/:id"
                  all: 
                    method: "GET"
                    path: "/:lang/researches"
                  create:
                    method: "POST"
                    path: "/:lang/researches"
                  update:
                    method: "PUT"
                    path: "/:lang/researches/:id"
                  remove:
                    method: "DELETE"
                    path: "/:lang/researches/:id"
              - name: "Scholastic"
                paths:
                  one:
                    method: "GET"
                    path: "/:lang/scholastic/:id"
                  all: 
                    method: "GET"
                    path: "/:lang/scholastic"
                  create:
                    method: "POST"
                    path: "/:lang/scholastic"
                  update:
                    method: "PUT"
                    path: "/:lang/scholastic/:id"
                  remove:
                    method: "DELETE"
                    path: "/:lang/scholastic/:id"
              - name: "Works"
                paths:
                  one:
                    method: "GET"
                    path: "/:lang/works/:id"
                  all: 
                    method: "GET"
                    path: "/:lang/works"
                  create:
                    method: "POST"
                    path: "/:lang/works"
                  update:
                    method: "PUT"
                    path: "/:lang/works/:id"
                  remove:
                    method: "DELETE"
                    path: "/:lang/works/:id"
  /health:
    get:
      summary: Health check
      tags:
      - "Health"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            properties:
              health:
                type: string
          examples:
            application/json:
              health: "Ok"
  /{lang}/contacts:
    get:
      summary: List All Contacts
      tags:
      - "Contact"
      security:
      - Bearer: []
      parameters:
        - name: "lang"
          description: "Lang of the content"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Contact'
          examples:
            application/json:
                data:
                  - id: "CON_ABC002"
                    icon: "icon-whatsapp"
                    img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Mensajeria/whatsapp.png"
                    info: "+54-263-4200-463" 
                    name: "Whatsapp"
                    order: 1
                    lang: "es"
                  - id: "CON_ABC001"
                    icon: "icon-telegram"
                    img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Mensajeria/telegram.png"
                    info: "caballerojavier13"
                    name: "Telegram"
                    order: 2
                    lang: "es"
    post:
      summary: Create a New Contact
      tags:
      - "Contact"
      security:
      - Bearer: []
      parameters:
        - name: "lang"
          description: "Lang of the content"
          in: "path"
          required: true
          type: "string"
        - in: body
          name: body
          required: true
          schema:
            type: object
            $ref: '#/definitions/ContactRequest'
            example:
              icon: "icon-whatsapp"
              img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Mensajeria/whatsapp.png"
              info: "+54-263-4200-463" 
              name: "Whatsapp"
              order: 1
              lang: "es"
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/Contact'
          examples:
            application/json:
              data:
                id: "CON_ABC002"
                icon: "icon-whatsapp"
                img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Mensajeria/whatsapp.png"
                info: "+54-263-4200-463" 
                name: "Whatsapp"
                order: 1
                lang: "es"
  /{lang}/contacts/{id}:
    get: 
      summary: Get a Contact
      tags:
      - "Contact"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            $ref: '#/definitions/Contact'
          examples:
            application/json:
                data:
                  id: "CON_ABC002"
                  icon: "icon-whatsapp"
                  img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Mensajeria/whatsapp.png"
                  info: "+54-263-4200-463" 
                  name: "Whatsapp"
                  order: 1
                  lang: "es"
    put: 
      summary: Edit a Contact
      tags:
      - "Contact"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - in: body
        name: body
        required: true
        schema:
          type: object
          $ref: '#/definitions/ContactRequest'
          example:
            icon: "icon-whatsapp"
            img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Mensajeria/whatsapp.png"
            info: "+54-263-4200-463" 
            name: "Whatsapp"
            order: 1
            lang: "es"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            $ref: '#/definitions/Contact'
          examples:
            application/json:
                data:
                  id: "CON_ABC002"
                  icon: "icon-whatsapp"
                  img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Mensajeria/whatsapp.png"
                  info: "+54-263-4200-463" 
                  name: "Whatsapp"
                  order: 1
                  lang: "es"
    delete: 
      summary: Delete a Contact
      tags:
      - "Contact"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        204:
          description: Successful Response
  /{lang}/educations:
    get:
      summary: List All Educations
      tags:
      - "Education"
      security:
      - Bearer: []
      parameters:
        - name: "lang"
          description: "Lang of the content"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Education'
          examples:
            application/json:
                data:
                  - id: "EDU_ABC003"
                    career: "Ingeniería en Sistemas de Información"
                    detail: "Promedio 8.22"
                    institute: "Universidad Tecnológica Nacional-Facultad Regional Mendoza"
                    time: "2010 - Actualidad"
                    order: 3
                    lang: "es"
                  - id: "EDU_ABC002"
                    career: "Humanidades y Ciencias Sociales con Orientación en Arte"
                    detail: "Segundo Escolta Nacional"
                    institute: "Instituto San Vicente de Paul"
                    time: "2005 - 2009"
                    order: 2
                    lang: "es"
                  - id: "EDU_ABC001"
                    career: ""
                    detail: "Abanderado Nacional - Alumno Destacado"
                    institute: "Escuela Dr. Segundo Llaver"
                    time: "1997 - 2004"
                    order: 1
                    lang: "es"
    post:
      summary: Create a New Education
      tags:
      - "Education"
      security:
      - Bearer: []
      parameters:
        - name: "lang"
          description: "Lang of the content"
          in: "path"
          required: true
          type: "string"
        - in: body
          name: body
          required: true
          schema:
            type: object
            $ref: '#/definitions/EducationRequest'
            example:
              career: "Ingeniería en Sistemas de Información"
              detail: "Promedio 8.22"
              institute: "Universidad Tecnológica Nacional-Facultad Regional Mendoza"
              time: "2010 - Actualidad"
              order: 3
              lang: "es"
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/Education'
          examples:
            application/json:
              data:
                id: "EDU_ABC003"
                career: "Ingeniería en Sistemas de Información"
                detail: "Promedio 8.22"
                institute: "Universidad Tecnológica Nacional-Facultad Regional Mendoza"
                time: "2010 - Actualidad"
                order: 3
                lang: "es"
  /{lang}/educations/{id}:
    get: 
      summary: Get a Education
      tags:
      - "Education"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            $ref: '#/definitions/Education'
          examples:
            application/json:
                data:
                  id: "EDU_ABC003"
                  career: "Ingeniería en Sistemas de Información"
                  detail: "Promedio 8.22"
                  institute: "Universidad Tecnológica Nacional-Facultad Regional Mendoza"
                  time: "2010 - Actualidad"
                  order: 3
                  lang: "es"
    put: 
      summary: Edit a Education
      tags:
      - "Education"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - in: body
        name: body
        required: true
        schema:
          type: object
          $ref: '#/definitions/EducationRequest'
          example:
            career: "Ingeniería en Sistemas de Información"
            detail: "Promedio 8.22"
            institute: "Universidad Tecnológica Nacional-Facultad Regional Mendoza"
            time: "2010 - Actualidad"
            order: 3
            lang: "es"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            $ref: '#/definitions/Education'
          examples:
            application/json:
                data:
                  id: "EDU_ABC003"
                  career: "Ingeniería en Sistemas de Información"
                  detail: "Promedio 8.22"
                  institute: "Universidad Tecnológica Nacional-Facultad Regional Mendoza"
                  time: "2010 - Actualidad"
                  order: 3
                  lang: "es"
    delete: 
      summary: Delete a Education
      tags:
      - "Education"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        204:
          description: Successful Response
  /{lang}/researches:
    get:
      summary: List All Researches
      tags:
      - "Research"
      security:
      - Bearer: []
      parameters:
        - name: "lang"
          description: "Lang of the content"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Research'
          examples:
            application/json:
                data:
                  - id: "RES_ABC002"
                    description: "Desarrollo del marco teórico, representación en congresos, e implementación del sistema."
                    group: "Laboratorio de Auditoría y Seguridad en TIC"
                    project: "Metamodelado de Auditoría y Reingeniería para Sistemas de Trazabilidad de Vinos"
                    time: "Enero 2016 - Actualidad"
                    order: 2
                    lang: "es"
                  - id: "RES_ABC001"
                    description: "Definición de algoritmos para la implementación de técnicas de testing formal."
                    group: "Laboratorio de Auditoría y Seguridad en TIC"
                    project: "Calidad de Software"
                    time: "Marzo 2014 - Diciembre 2015"
                    order: 1
                    lang: "es"
    post:
      summary: Create a New Research
      tags:
      - "Research"
      security:
      - Bearer: []
      parameters:
        - name: "lang"
          description: "Lang of the content"
          in: "path"
          required: true
          type: "string"
        - in: body
          name: body
          required: true
          schema:
            type: object
            $ref: '#/definitions/ResearchRequest'
            example:
              description: "Desarrollo del marco teórico, representación en congresos, e implementación del sistema."
              group: "Laboratorio de Auditoría y Seguridad en TIC"
              project: "Metamodelado de Auditoría y Reingeniería para Sistemas de Trazabilidad de Vinos"
              time: "Enero 2016 - Actualidad"
              order: 2
              lang: "es"
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/Research'
          examples:
            application/json:
              data:
                id: "RES_ABC002"
                description: "Desarrollo del marco teórico, representación en congresos, e implementación del sistema."
                group: "Laboratorio de Auditoría y Seguridad en TIC"
                project: "Metamodelado de Auditoría y Reingeniería para Sistemas de Trazabilidad de Vinos"
                time: "Enero 2016 - Actualidad"
                order: 2
                lang: "es"
  /{lang}/researches/{id}:
    get: 
      summary: Get a Research
      tags:
      - "Research"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            $ref: '#/definitions/Research'
          examples:
            application/json:
                data:
                  id: "RES_ABC002"
                  description: "Desarrollo del marco teórico, representación en congresos, e implementación del sistema."
                  group: "Laboratorio de Auditoría y Seguridad en TIC"
                  project: "Metamodelado de Auditoría y Reingeniería para Sistemas de Trazabilidad de Vinos"
                  time: "Enero 2016 - Actualidad"
                  order: 2
                  lang: "es"
    put: 
      summary: Edit a Research
      tags:
      - "Research"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - in: body
        name: body
        required: true
        schema:
          type: object
          $ref: '#/definitions/ResearchRequest'
          example:
            description: "Desarrollo del marco teórico, representación en congresos, e implementación del sistema."
            group: "Laboratorio de Auditoría y Seguridad en TIC"
            project: "Metamodelado de Auditoría y Reingeniería para Sistemas de Trazabilidad de Vinos"
            time: "Enero 2016 - Actualidad"
            order: 2
            lang: "es"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            $ref: '#/definitions/Research'
          examples:
            application/json:
                data:
                  id: "RES_ABC002"
                  description: "Desarrollo del marco teórico, representación en congresos, e implementación del sistema."
                  group: "Laboratorio de Auditoría y Seguridad en TIC"
                  project: "Metamodelado de Auditoría y Reingeniería para Sistemas de Trazabilidad de Vinos"
                  time: "Enero 2016 - Actualidad"
                  order: 2
                  lang: "es"
    delete: 
      summary: Delete a Research
      tags:
      - "Research"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        204:
          description: Successful Response
  /{lang}/scholastic:
    get:
      summary: List All Scholastic
      tags:
      - "Scholastic"
      security:
      - Bearer: []
      parameters:
        - name: "lang"
          description: "Lang of the content"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Scholastic'
          examples:
            application/json:
                data:
                  - id: "SCH_ABC002"
                    description: "Ayudante de Cátedra de 2da Ad-Honorem"
                    institute: "Universidad Tecnológica Nacional-Facultad Regional Mendoza"
                    subject: "Ingeniería en Sistemas de Información-Sistemas de Representación"
                    time: "Marzo 2014 - Actualidad"
                    lang: "es"
                    order: 2
                  - id: "SCH_ABC001"
                    description: "Ayudante de Cátedra de 2da Ad-Honorem"
                    institute: "Universidad Tecnológica Nacional-Facultad Regional Mendoza"
                    subject: "Ingeniería en Sistemas de Información-Paradigmas de Programación"
                    time: "Julio 2012 - Julio 2013"
                    lang: "es"
                    order: 1
    post:
      summary: Create a New Scholastic
      tags:
      - "Scholastic"
      security:
      - Bearer: []
      parameters:
        - name: "lang"
          description: "Lang of the content"
          in: "path"
          required: true
          type: "string"
        - in: body
          name: body
          required: true
          schema:
            type: object
            $ref: '#/definitions/ScholasticRequest'
            example:
              description: "Ayudante de Cátedra de 2da Ad-Honorem"
              institute: "Universidad Tecnológica Nacional-Facultad Regional Mendoza"
              subject: "Ingeniería en Sistemas de Información-Sistemas de Representación"
              time: "Marzo 2014 - Actualidad"
              lang: "es"
              order: 2
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/Scholastic'
          examples:
            application/json:
              data:
                id: "SCH_ABC002"
                description: "Ayudante de Cátedra de 2da Ad-Honorem"
                institute: "Universidad Tecnológica Nacional-Facultad Regional Mendoza"
                subject: "Ingeniería en Sistemas de Información-Sistemas de Representación"
                time: "Marzo 2014 - Actualidad"
                lang: "es"
                order: 2
  /{lang}/scholastic/{id}:
    get: 
      summary: Get a Scholastic
      tags:
      - "Scholastic"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            $ref: '#/definitions/Scholastic'
          examples:
            application/json:
                data:
                  id: "SCH_ABC002"
                  description: "Ayudante de Cátedra de 2da Ad-Honorem"
                  institute: "Universidad Tecnológica Nacional-Facultad Regional Mendoza"
                  subject: "Ingeniería en Sistemas de Información-Sistemas de Representación"
                  time: "Marzo 2014 - Actualidad"
                  lang: "es"
                  order: 2
    put: 
      summary: Edit a Scholastic
      tags:
      - "Scholastic"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - in: body
        name: body
        required: true
        schema:
          type: object
          $ref: '#/definitions/ScholasticRequest'
          example:
            description: "Ayudante de Cátedra de 2da Ad-Honorem"
            institute: "Universidad Tecnológica Nacional-Facultad Regional Mendoza"
            subject: "Ingeniería en Sistemas de Información-Sistemas de Representación"
            time: "Marzo 2014 - Actualidad"
            lang: "es"
            order: 2
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            $ref: '#/definitions/Scholastic'
          examples:
            application/json:
                data:
                  id: "SCH_ABC002"
                  description: "Ayudante de Cátedra de 2da Ad-Honorem"
                  institute: "Universidad Tecnológica Nacional-Facultad Regional Mendoza"
                  subject: "Ingeniería en Sistemas de Información-Sistemas de Representación"
                  time: "Marzo 2014 - Actualidad"
                  lang: "es"
                  order: 2
    delete: 
      summary: Delete a Scholastic
      tags:
      - "Scholastic"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        204:
          description: Successful Response
  /{lang}/social-networks:
    get:
      summary: List All SocialNetwork
      tags:
      - "SocialNetwork"
      security:
      - Bearer: []
      parameters:
        - name: "lang"
          description: "Lang of the content"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/SocialNetwork'
          examples:
            application/json:
                data:
                  - id: "SOC_ABC001"
                    img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Redes_Sociales/facebook.png"
                    link: "https://www.facebook.com/caballerojavier13"
                    name: "Facebook"
                    order: 1
                    lang: "es"
                  - id: "SOC_ABC002"
                    img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Redes_Sociales/instagram.png"
                    link: "https://instagram.com/caballerojavier13/"
                    name: "Instagram"
                    order: 2
                    lang: "es"
                    
    post:
      summary: Create a New SocialNetwork
      tags:
      - "SocialNetwork"
      security:
      - Bearer: []
      parameters:
        - name: "lang"
          description: "Lang of the content"
          in: "path"
          required: true
          type: "string"
        - in: body
          name: body
          required: true
          schema:
            type: object
            $ref: '#/definitions/SocialNetworkRequest'
            example:
              img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Redes_Sociales/facebook.png"
              link: "https://www.facebook.com/caballerojavier13"
              name: "Facebook"
              order: 1
              lang: "es"
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/SocialNetwork'
          examples:
            application/json:
              data:
                id: "SOC_ABC001"
                img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Redes_Sociales/facebook.png"
                link: "https://www.facebook.com/caballerojavier13"
                name: "Facebook"
                order: 1
                lang: "es"
  /{lang}/social-networks/{id}:
    get: 
      summary: Get a SocialNetwork
      tags:
      - "SocialNetwork"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            $ref: '#/definitions/SocialNetwork'
          examples:
            application/json:
                data:
                  id: "SOC_ABC001"
                  img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Redes_Sociales/facebook.png"
                  link: "https://www.facebook.com/caballerojavier13"
                  name: "Facebook"
                  order: 1
                  lang: "es"
    put: 
      summary: Edit a SocialNetwork
      tags:
      - "SocialNetwork"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - in: body
        name: body
        required: true
        schema:
          type: object
          $ref: '#/definitions/SocialNetworkRequest'
          example:
            img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Redes_Sociales/facebook.png"
            link: "https://www.facebook.com/caballerojavier13"
            name: "Facebook"
            order: 1
            lang: "es"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            $ref: '#/definitions/SocialNetwork'
          examples:
            application/json:
                data:
                  id: "SOC_ABC001"
                  img: "https://s3.amazonaws.com/caballerojavier13-pages-files/personal_page/Redes_Sociales/facebook.png"
                  link: "https://www.facebook.com/caballerojavier13"
                  name: "Facebook"
                  order: 1
                  lang: "es"
    delete: 
      summary: Delete a SocialNetwork
      tags:
      - "SocialNetwork"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        204:
          description: Successful Response
  /{lang}/works:
    get:
      summary: List All Works
      tags:
      - "Work"
      security:
      - Bearer: []
      parameters:
        - name: "lang"
          description: "Lang of the content"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Work'
          examples:
            application/json:
                data:
                  - id: "WOR_ABC004"
                    company: "Globant"
                    description: "Ingeniero en calidad de juegos (GQE game quality engineer), para Disney en proyectos de video juegos para iOS y Android. Encargado de automatización de pruebas."
                    position: "Tester Automation Engineer"
                    order: 4
                    time: "Agosto 2017 - Actualidad"
                    lang: "es"
                  - id: "WOR_ABC003"
                    company: "Aconcagua Software Factory"
                    description: "Gestión de calidad para proyectos de Mercadopago. Métricas con Google Analytics, Hotjar, New Relic, DataDog, Rollbar. Análisis de la calidad del código. Configuración de alarmas de detección de fraude, fallas, defectos, inconsistencia de datos, etc."
                    position: "Quality Assurance - Business Assurance"
                    order: 3
                    time: "Octubre 2015 - Agosto 2017"
                    lang: "es"
                  - id: "WOR_ABC002"
                    company: "Aconcagua Software Factory"
                    description: "Reporte de estado de proyectos, análisis de asignación de personal, análisis de productividad, definición de procesos, control de procesos, seguimiento y auditoría CMMI."
                    position: "Project Manager Officer - QA Analist (CMMI)"
                    order: 2
                    time: "Octubre 2015 - Junio 2016"
                    lang: "es"
                  - id: "WOR_ABC001"
                    company: "Aconcagua Software Factory"
                    description: "Análisis de requerimientos, diseño de casos de prueba, ejecución de casos de pruebas, seguimiento de defectos. Automatización de pruebas."
                    position: "QC Tester"
                    order: 2
                    time: "Febrero 2014 - Febrero 2016"
                    lang: "es"
    post:
      summary: Create a New Work
      tags:
      - "Work"
      security:
      - Bearer: []
      parameters:
        - name: "lang"
          description: "Lang of the content"
          in: "path"
          required: true
          type: "string"
        - in: body
          name: body
          required: true
          schema:
            type: object
            $ref: '#/definitions/WorkRequest'
            example:
              company: "Globant"
              description: "Ingeniero en calidad de juegos (GQE game quality engineer), para Disney en proyectos de video juegos para iOS y Android. Encargado de automatización de pruebas."
              position: "Tester Automation Engineer"
              order: 4
              time: "Agosto 2017 - Actualidad"
              lang: "es"
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/Work'
          examples:
            application/json:
              data:
                id: "WOR_ABC004"
                company: "Globant"
                description: "Ingeniero en calidad de juegos (GQE game quality engineer), para Disney en proyectos de video juegos para iOS y Android. Encargado de automatización de pruebas."
                position: "Tester Automation Engineer"
                order: 4
                time: "Agosto 2017 - Actualidad"
                lang: "es"
  /{lang}/works/{id}:
    get: 
      summary: Get a Work
      tags:
      - "Work"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            $ref: '#/definitions/Work'
          examples:
            application/json:
                data:
                  id: "WOR_ABC004"
                  company: "Globant"
                  description: "Ingeniero en calidad de juegos (GQE game quality engineer), para Disney en proyectos de video juegos para iOS y Android. Encargado de automatización de pruebas."
                  position: "Tester Automation Engineer"
                  order: 4
                  time: "Agosto 2017 - Actualidad"
                  lang: "es"
    put: 
      summary: Edit a Work
      tags:
      - "Work"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - in: body
        name: body
        required: true
        schema:
          type: object
          $ref: '#/definitions/WorkRequest'
          example:
            company: "Globant"
            description: "Ingeniero en calidad de juegos (GQE game quality engineer), para Disney en proyectos de video juegos para iOS y Android. Encargado de automatización de pruebas."
            position: "Tester Automation Engineer"
            order: 4
            time: "Agosto 2017 - Actualidad"
            lang: "es"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            $ref: '#/definitions/Work'
          examples:
            application/json:
                data:
                  id: "WOR_ABC004"
                  company: "Globant"
                  description: "Ingeniero en calidad de juegos (GQE game quality engineer), para Disney en proyectos de video juegos para iOS y Android. Encargado de automatización de pruebas."
                  position: "Tester Automation Engineer"
                  order: 4
                  time: "Agosto 2017 - Actualidad"
                  lang: "es"
    delete: 
      summary: Delete a Work
      tags:
      - "Work"
      security:
      - Bearer: []
      parameters:
      - name: "lang"
        description: "Lang of the content"
        in: "path"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        204:
          description: Successful Response
securityDefinitions:
  Bearer:
    description: "For accessing the API a valid token must be passed in all the queries.\
      \ The following syntax must be used in the 'Authorization' header :\n\n    Bearer:\
      \ xxxxxx.yyyyyyy.zzzzzz\n"
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  Contact:
    title: Contact
    type: object
    properties:
      id:
        type: string
      icon:
        type: string
      img:
        type: string
      name:
        type: string
      lang:
        type: string
      info:
        type: string
      order:
        type: integer
        minimum: 0
    required:
    - icon
    - img
    - info
    - lang
    - name
    - order
  ContactRequest:
    title: Contact
    type: object
    properties:
      icon:
        type: string
      img:
        type: string
      name:
        type: string
      lang:
        type: string
      info:
        type: string
      order:
        type: integer
        minimum: 0
    required:
    - icon
    - img
    - info
    - lang
    - name
    - order
  Education:
    title: Education
    type: object
    properties:
      id:
        type: string
      career:
        type: string
      detail:
        type: string
      institute:
        type: string
      lang:
        type: string
      order:
        type: integer
        minimum: 0
      time:
        type: string
    required:
      - detail
      - institute
      - lang
      - order
      - time
  EducationRequest:
    title: Education
    type: object
    properties:
      career:
        type: string
      detail:
        type: string
      institute:
        type: string
      lang:
        type: string
      order:
        type: integer
        minimum: 0
      time:
        type: string
    required:
      - detail
      - institute
      - lang
      - order
      - time
  Research:
    title: Research
    type: object
    properties:
      id:
        type: string
      group:
        type: string
      description:
        type: string
      project:
        type: string
      lang:
        type: string
      order:
        type: integer
        minimum: 0
      time:
        type: string
    required:
      - group
      - project
      - description
      - lang
      - order
      - time
  ResearchRequest:
    title: Research
    type: object
    properties:
      group:
        type: string
      description:
        type: string
      project:
        type: string
      lang:
        type: string
      order:
        type: integer
        minimum: 0
      time:
        type: string
    required:
      - group
      - project
      - description
      - lang
      - order
      - time
  ServiceRestFull:
    title: ServiceRestFull
    type: object
    properties:
      name:
        type: string
      paths:
        type: object
        properties:
          one:
            $ref: '#/definitions/EndPoint'
          all:
            $ref: '#/definitions/EndPoint'
          create:
            $ref: '#/definitions/EndPoint'
          update:
            $ref: '#/definitions/EndPoint'
          remove:
            $ref: '#/definitions/EndPoint'
  EndPoint:
    title: EndPoint
    type: object
    properties:
      method: 
        type: string
      path:
        type: string
  Scholastic:
    title: Scholastic
    type: object
    properties:
      id:
        type: string
      institute:
        type: string
      description:
        type: string
      subject:
        type: string
      lang:
        type: string
      order:
        type: integer
        minimum: 0
      time:
        type: string
    required:
      - institute
      - subject
      - description
      - lang
      - order
      - time
  ScholasticRequest:
    title: Scholastic
    type: object
    properties:
      institute:
        type: string
      description:
        type: string
      subject:
        type: string
      lang:
        type: string
      order:
        type: integer
        minimum: 0
      time:
        type: string
    required:
      - institute
      - subject
      - description
      - lang
      - order
      - time
  SocialNetwork:
    title: SocialNetwork
    type: object
    properties:
      id:
        type: string
      link:
        type: string
      img:
        type: string
      name:
        type: string
      lang:
        type: string
      order:
        type: integer
        minimum: 0
    required:
    - link
    - img
    - lang
    - name
    - order
  SocialNetworkRequest:
    title: SocialNetwork
    type: object
    properties:
      link:
        type: string
      img:
        type: string
      name:
        type: string
      lang:
        type: string
      order:
        type: integer
        minimum: 0
    required:
    - link
    - img
    - lang
    - name
    - order
  Work:
    title: Work
    type: object
    properties:
      id:
        type: string
      company:
        type: string
      description:
        type: string
      lang:
        type: string
      position:
        type: string
      order:
        type: integer
        minimum: 0
      time:
        type: string
    required:
      - company
      - description
      - lang
      - order
      - position
      - time
  WorkRequest:
    title: Work
    type: object
    properties:
      company:
        type: string
      description:
        type: string
      lang:
        type: string
      position:
        type: string
      order:
        type: integer
        minimum: 0
      time:
        type: string
    required:
      - company
      - description
      - lang
      - order
      - position
      - time